# -*- coding: utf-8 -*-
"""question_answering_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y8-OZDYw5ClBisjooa494FHLgmdinzJU
"""

# !pip install cdqa

import os
import pandas as pd
from ast import literal_eval

from cdqa.utils.converters import pdf_converter
from cdqa.pipeline import QAPipeline
from cdqa.utils.download import download_model

download_model(model="bert-squad_1.1",dir="./models")

df=pdf_converter(directory_path="./data/")

df.head()

pd.set_option("display.max_colwidth",-1)
df.head()

cdqa_pipeline=QAPipeline(reader="./models/bert_qa.joblib",max_df=1.0)
cdqa_pipeline.fit_retriever(df=df)

quaery="What is my name?"
prediction=cdqa_pipeline.predict(quaery)

prediction

quaery="What are the skills of saranga?"
prediction=cdqa_pipeline.predict(quaery)

prediction

quaery="How old is he?"
prediction=cdqa_pipeline.predict(quaery,3)

prediction

quaery="What kind of person he is?"
prediction=cdqa_pipeline.predict(quaery,3)

prediction

quaery="Working experience of saranga?"
prediction=cdqa_pipeline.predict(quaery,3)

prediction

quaery="Education Qualifications of saranga?"
prediction=cdqa_pipeline.predict(quaery,3)

prediction

